version: "3.9"

services:
  mongo:
    image: mongo:5.0.5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: msn_
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    networks:
      - msn-network

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: msn_
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_password
    networks:
      - msn-network

  grafana:
    image: grafana/grafana:8.3.3
    restart: always
    ports:
      - "3000:3000"

networks:
  msn-network:
    driver: bridge
