version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine3.15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: msn
      POSTGRES_DB: msn
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgresql_data:


networks:
  postgres:
